
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author steph
 */
public class RetiroMovil extends javax.swing.JFrame {
    private Principal principal;
    private Cuenta cuenta;
    /**
     * Creates new form RetiroMovil
     */
    public RetiroMovil() {
        initComponents();
        principal = Principal.getInstance();
        cuenta = principal.getCuenta();
        double saldoActual = cuenta.getSaldo();
        txtSaldo.setText("$" + String.format("%.2f", saldoActual));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConfiRetiro = new javax.swing.JButton();
        txtMontoRetiro = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfiRetiro.setBackground(new java.awt.Color(0, 148, 86));
        btnConfiRetiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfiRetiro.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiRetiro.setText("Confirmar");
        btnConfiRetiro.setBorder(null);
        btnConfiRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiRetiroActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfiRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 276, 230, 40));

        txtMontoRetiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMontoRetiro.setBorder(null);
        jPanel1.add(txtMontoRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, 30));

        txtSaldo.setEditable(false);
        txtSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSaldo.setBorder(null);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/RetiroMovil.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void btnConfiRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiRetiroActionPerformed
        // TODO add your handling code here:
        String importeTexto = txtMontoRetiro.getText();
    
    try {
        double importe = Double.parseDouble(importeTexto); // Convertir a double
        
        if (importe > cuenta.getSaldo()) {
            JOptionPane.showMessageDialog(this, "Saldo insuficiente", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Confirmar retiro
            int response = JOptionPane.showConfirmDialog(this, "Vas a retirar: $" + importe + "\n¿Deseas continuar?", 
                                                         "Confirmar Retiro", JOptionPane.OK_CANCEL_OPTION);
            // Si el usuario presiona Aceptar
            if (response == JOptionPane.OK_OPTION) {
                principal.executeInBanca(() -> {
                    cuenta.retirar("Banca",importe);
                    System.out.println("Retiro realizado en: " + Thread.currentThread().getName());
                    SwingUtilities.invokeLater(() -> {
                        // Crear un JPanel personalizado para el mensaje
                        JPanel panel = new JPanel();
                        JLabel label = new JLabel("Retirando...");
                        panel.add(label);

                        // Crear el diálogo sin botones
                        final JDialog dialog = new JDialog(this, "Retiro en Proceso", true);
                        dialog.setContentPane(panel);
                        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                        dialog.setSize(200, 100);
                        dialog.setLocationRelativeTo(this);

                        // Crear un temporizador para cerrar el diálogo después de 3 segundos
                        Timer timer = new Timer(1000, new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                dialog.setVisible(false);
                                dialog.dispose();

                                // Abrir la ventana del menú principal y cerrar la ventana actual
                                SwingUtilities.invokeLater(new Runnable() {
                                    @Override
                                    public void run() {
                                       new MenuMovil().setVisible(true); // Cambiar a la ventana del menú
                                       dispose();
                                    }
                                });
                            }
                        });
                        timer.setRepeats(false); // El temporizador solo se ejecutará una vez

                        // Mostrar el diálogo y comenzar el temporizador
                        timer.start();
                        dialog.setVisible(true);
                    });
                });
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfiRetiroActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetiroMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetiroMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetiroMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetiroMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetiroMovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMontoRetiro;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
