
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author steph
 */
public class TransferirMovil extends javax.swing.JFrame {
    private Principal principal;
    private Cuenta cuenta;
    /**
     * Creates new form TransferirMovil
     */
    public TransferirMovil() {
        initComponents();
        principal = Principal.getInstance();
        cuenta = principal.getCuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMonto = new javax.swing.JTextField();
        btnConfiTransferir = new javax.swing.JButton();
        txtCuenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMonto.setBorder(null);
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, 30));

        btnConfiTransferir.setBackground(new java.awt.Color(0, 148, 86));
        btnConfiTransferir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfiTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiTransferir.setText("Confirmar");
        btnConfiTransferir.setBorder(null);
        btnConfiTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfiTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 276, 230, 40));

        txtCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCuenta.setBorder(null);
        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/TransferirMovil.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void btnConfiTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiTransferirActionPerformed
        // TODO add your handling code here:
        String importeTexto = txtMonto.getText();
        String cuentatxt = txtCuenta.getText();

        if (cuentatxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de cuenta", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (importeTexto.isEmpty() || importeTexto.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                double importe = Double.parseDouble(importeTexto); // Convertir a double

                if (importe > cuenta.getSaldo()) {
                    JOptionPane.showMessageDialog(this, "Saldo insuficiente", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    int response = JOptionPane.showConfirmDialog(this, "Vas a transferir: $" + importe + " a la cuenta: " + cuentatxt + "\n¿Deseas continuar?",
                            "Confirmar Transferencia", JOptionPane.OK_CANCEL_OPTION);
                    if (response == JOptionPane.OK_OPTION) {
                        principal.executeInBanca(() -> {
                            cuenta.retirar("Banca", importe);
                            System.out.println("Transferencia realizada en: " + Thread.currentThread().getName());
                            SwingUtilities.invokeLater(() -> {
                                JPanel panel = new JPanel();
                                JLabel label = new JLabel("Transferencia exitosa");
                                panel.add(label);

                                final JDialog dialog = new JDialog(this, "Transferencia en Proceso", true);
                                dialog.setContentPane(panel);
                                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                                dialog.setSize(200, 100);
                                dialog.setLocationRelativeTo(this);

                                Timer timer = new Timer(1000, new ActionListener() {
                                    @Override
                                    public void actionPerformed(ActionEvent e) {
                                        dialog.setVisible(false);
                                        dialog.dispose();

                                        SwingUtilities.invokeLater(new Runnable() {
                                            @Override
                                            public void run() {
                                                new MenuMovil().setVisible(true); // Cambiar a la ventana del menú
                                                dispose();
                                            }
                                        });
                                    }
                                });
                                timer.setRepeats(false);
                                timer.start();
                                dialog.setVisible(true);
                            });
                        });
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto válido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
         
    }//GEN-LAST:event_btnConfiTransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferirMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferirMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferirMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferirMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferirMovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
